### ISSUE TITLE
The class loader can be automated

### ISSUE THREAD

**Issue by dbalabka** [vladimmi/construct-static#2]
You can use `composer.json` to register file 
https://github.com/NxtLvLSoftware/php-static-constructors/blob/master/composer.json#L20
with new custom loader registration:
https://github.com/NxtLvLSoftware/php-static-constructors/blob/master/hook.php#L39

**Comment by vladimmi** [comment]
@dbalabka Does it work reliable enough to be added as auto-register? It wraps all autoloaders at the moment of init, but I guess that can fail if some more autoloaders added later - and then end-user is out of control...

**Comment by dbalabka** [comment]
@vladimmi you probably right that it should be controlled by the end-user. Too many "ifs" should be taken into account.
