### ISSUE TITLE
Static constructor called multiple times when inheriting

### ISSUE THREAD

**Issue by smenardstingray** [vladimmi/construct-static#3]
I have some inheritance and because of that, the ``__constructStatic`` is called more than once. This is not an expected behavior.

In the callConstruct, I've added a new condition:
```
if ($reflectionMethod->isStatic() && $className === $reflectionMethod->getDeclaringClass()->getName()) {
```

**Comment by vladimmi** [comment]
Oh, I didn't thought about inheritance at that moment, thanks for suggestion, I'll update the condition too.
